- block:
  - name: Enable extras repo
    shell: yum-config-manager --enable rhui-REGION-rhel-server-extras

  - name: Enable EPEL
    package:
      name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
      state: present

  - name: Update system
    yum:
      name: '*'
      state: latest

  - name: Install docker and other useful packages
    package:
      name:
      - docker
      - git
      - ansible
      - python-openshift
      state: present

  - name: Configure docker storage
    copy:
      content: |
               STORAGE_DRIVER=""
      dest: /etc/sysconfig/docker-storage-setup

  - name: Created docker group
    group:
      name: docker
      state: present

  - name: Added ec2-user to group
    user:
      name: ec2-user
      groups: docker

  - name: Add insecure registry for openshift
    replace:
      path: /etc/sysconfig/docker
      regexp: "OPTIONS='--selinux-enabled"
      replace: "OPTIONS='--insecure-registry 172.30.0.0/16 --selinux-enabled"

  - name: Start and enable docker
    systemd:
      name: docker
      state: started
      enabled: true
    notify: ssh-info

  - name: Copy tmpfiles.d file for modification 
    copy:
      src: /usr/lib/tmpfiles.d/tmp.conf
      dest: /etc/tmpfiles.d/tmp.conf
      remote_src: yes

  - name: Exclude our openshift mount from tmpreaper/tmpwatch
    lineinfile:
      path: /etc/tmpfiles.d/tmp.conf
      insertafter: '^X.*$'
      line: 'x /tmp/openshift.local.clusterup'
  become: true

- name: Reset ssh connection to allow user changes to take affect
  meta: reset_connection

- name: Update facts to pick up new interface
  setup:

- name: Update openshift defaults
  set_fact:
    openshift_setup_ip: "{{ inventory_hostname }}"
