- name: cluster-info
  debug:
    msg:
    - "You cluster console is available at https://{{ openshift_setup_hostname }}:8443/console"
    - "You can also login via CLI with:"
    -  "oc login -u {{ openshift_setup_user }} -p {{ openshift_setup_user_password }} https://{{ openshift_setup_hostname }}:8443 --insecure-skip-tls-verify=true"
